name: Testing Jupyter Notebooks

on:
#  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_strategy_matrix:
    runs-on: ubuntu-latest
    # let's not run this on every fork, change to your fork when developing
#    if: github.repository == 'mlrun/functions' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Matrix
      id: set-matrix
      run: |
        matrix=$(find . -name "*.ipynb" | jq -R -s 'split("\n")[:-1]')
        echo "${matrix}"
        echo "{matrix}=${matrix}"
        
    outputs:
      matrix: ${{matrix}}

  run_notebooks:
    needs: build_strategy_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{needs.build_strategy_matrix.outputs.matrix}}
    steps:
      - name: run-notebooks
        run: |
          jupyter nbconvert --to notebook --execute ${{ matrix.package }} --ExecutePreprocessor.kernel_name=python3 --output=${{ matrix.package }}
      
      




