name: Notebook Matrix

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix

      id: matrix
      run: |
        matrix=$(find . -name "*.ipynb" -type f)
        echo "::set-output name=matrix::${matrix}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


  use-matrix:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        matrix="${{ needs.build.outputs.matrix }}"
        echo "Matrix: $matrix"