name: Notebook Matrix

on:
  workflow_dispatch:
  push:

#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    outputs:
#      nb_matrix: ${{ steps.matrix.outputs.nb_matrix }}
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#
#    - name: Generate Notebook Matrix
#
#      id: matrix
#      run: |
#        matrix=$(find . -name "*.ipynb" -type f)
#        echo "nb_matrix=${{  matrix  }}" >> $GITHUB_OUTPUT
#
#
#  use-matrix:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - name: Use Notebook Matrix
#      run: |
#        matrix="${{ needs.build.outputs.nb_matrix }}"
#        echo "Matrix: $matrix"
#
#        for notebook in $(echo "$matrix" | jq -r '.[]'); do
#                    echo "Found notebook: $notebook"
#                    # Your further processing here
#                done

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}