name: Notebook Matrix

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
      # or use 'brew install jq' for macOS

    - name: Generate Notebook Matrix
      id: matrix
      run: |
        find . -name "*.ipynb" | jq -R -s 'split("\n")[:-1]' > notebook_matrix.json
        echo "::set-output name=matrix::$(cat notebook_matrix.json)"
        echo "{matrix}={$(cat notebook_matrix.json)}" >> $GITHUB_OUTPUT

    - name: Use Notebook Matrix
      run: |
        echo "Matrix: ${{ steps.matrix.outputs.matrix }}"
        # You can use the matrix variable in your subsequent steps as needed