name: Notebook Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.matrix.outputs.nb_matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix

      id: matrix
      run: |
        matrix=$(find . -name "*.ipynb" -type f)
        echo "nb-matrix=${{  matrix  }}" >> $GITHUB_OUTPUT


  use-matrix:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        matrix="${{ needs.build.outputs.output1 }}"
        echo "Matrix: $matrix"
        
        for notebook in $(echo "$matrix" | jq -r '.[]'); do
                    echo "Found notebook: $notebook"
                    # Your further processing here
                done