name: Notebook Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      nb_matrix: ${ steps.matrix.outputs.nb_matrix }
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix
      id: matrix
      run: |
        echo "nb_matrix=$(find . -name "*.ipynb" -type f)"
        
        matrix=$((
            echo '{ "notebooks" : ['
            find . -name "*.ipynb" -type f | sort | uniq
            echo " ]}"
          ) | jq 'del(.[][] | select(. == ""))'  -c)


  use-matrix:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        matrix="${{ fromJSON(needs.build.outputs.nb_matrix) }}"
        echo "Matrix notebooks: ${{  matrix.notebooks  }}"
        
        for notebook in $(echo ${{  matrix.notebooks  }} | jq -r '.[]'); do
                    echo "Found notebook: $notebook"
                    # Your further processing here
                done