name: Testing Jupyter Notebooks

on:
#  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_strategy_matrix:
    runs-on: ubuntu-latest
    # let's not run this on every fork, change to your fork when developing
#    if: github.repository == 'mlrun/functions' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Matrix
      id: set-matrix
      run: |
        notebooks=$(find . -name "*.ipynb") \
        # Initialize an empty JSON array \
        matrix="[" \
        first=true \
        
        # Loop through each notebook file \
        for notebook in $notebooks; do \
            # Check if it's the first file in the matrix \
            if [ "$first" = true ]; then \ 
                first=false \
            else \
                # Add a comma separator between elements in the matrix \
                matrix="${matrix}," \
            fi \
        
            # Add the filename to the matrix in JSON format \
            matrix="${matrix}\"${notebook}\"" \ 
        done \
        
        # Close the JSON array \
        matrix="${matrix}]" \
        
        # Print the matrix \
        echo "${matrix}"
        
    outputs:
      matrix: "my_matrix"





