name: Notebook Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      nbmatrix: ${ steps.matrix.outputs.nbmatrix }
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix
      id: matrix
      run: |        
        nbmatrix=$((
            echo '{ "notebooks" : ['
            echo $(find . -name "*.ipynb" -print | sed 's,/*[^/]\+/*$,,' | sort | uniq | sed 's/.*/"&"/'  | sed '$!s/.*/&,/')
            echo " ]}"
          ) | jq 'del(.[][] | select(. == ""))'  -c)
        echo $nbmatrix
        echo "nbmatrix={\"include\":$(echo nbmatrix)}" >> $GITHUB_OUTPUT

  use-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.nbmatrix)}}

    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        echo "Matrix notebooks: ${{  matrix.include  }}"
        
        for notebook in $(echo ${{  matrix.include  }} | jq -r '.[]'); do
                    echo "Found notebook: $notebook"
                    # Your further processing here
                done