name: Notebook Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      nbmatrix: ${ steps.matrix.outputs.nbmatrix }
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix
      id: matrix
      run: |        
        nbmatrix=$((
            echo '{ "notebooks" : ['
            echo $(find . -name "*.ipynb" -print | sed 's,/*[^/]\+/*$,,' | sort | uniq | sed 's/.*/"&"/'  | sed '$!s/.*/&,/')
            echo " ]}"
          ) | jq 'del(.[][] | select(. == ""))'  -c)
        echo $nbmatrix
        echo "nbmatrix=${nbmatrix}" > $GITHUB_OUTPUT


  check_matrix:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml
      - name: Check matrix definition
        run: |
          nbmatrix='${{needs.build.outputs.nbmatrix.notebooks}}'
          echo nbmatrix
          echo nbmatrix | jq .
          echo nbmatrix | json2yaml

  use-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.nbmatrix.notebooks)}}

    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        echo "Matrix notebooks: ${{  matrix.notebooks  }}"
        
        for notebook in $(echo ${{  matrix.notebooks  }} | jq -r '.[]'); do
                    echo "Found notebook: $notebook"
                    # Your further processing here
                done