name: Notebook Matrix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix
      id: matrix
      run: |
        matrix=$(find . -name "*.ipynb" -type f)
        echo "::set-output name=matrix::${matrix}"

    - name: Use Notebook Matrix
      run: |
        matrix="${{ steps.matrix.outputs.matrix }}"
        echo "Matrix: $matrix"
        # You can use the matrix variable in your subsequent steps as needed