name: Notebook Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      nb_matrix: ${ steps.matrix.outputs.nb_matrix }
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Notebook Matrix
      id: matrix
      run: |        
        nb_matrix=$(
            echo '{ "notebooks" : ['
            find . -name "*.ipynb" -print | sed 's,/*[^/]\+/*$,,' | sort | uniq | sed 's/.*/"&"/'  | sed '$!s/.*/&,/'
            echo " ]}"
          ) 
        echo $nb_matrix


  use-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.build.outputs.nb_matrix) }}
    needs: build
    steps:
    - name: Use Notebook Matrix
      run: |
        echo "Matrix notebooks: ${{  matrix.notebooks  }}"
        
        for notebook in $(echo ${{  matrix.notebooks  }} | jq -r '.[]'); do
                    echo "Found notebook: $notebook"
                    # Your further processing here
                done